# coding:utf-8
"""
Model alias constants (stub — to be populated).
"""


class LTT:
    """LTT alias constants (stub)."""
    pass
    QUADRANT_PUSH_CREDIT = 'QuadPushCred'
    MAINSTREAM_LEADIN_VAR5 = 'MsLeadinVar5'
    MAINSTREAM_LEADIN_ENTRY = 'MsLeadinEntry'
    QUADRANT_ZEN_DASH_COUNT = '4QuadZenDCnt'
    ONE_QUADRANT_UPRISING_TIMING_LAG_MAJOR = '1QUprLagMaj'
    QUADRANT_LEVERAGE_MACD_TIMING_LAG_DUMMY = 'QLevMACDLagD'
    QUADRANT_M9T_DEADPOOL_COUNT = '4QuadM9TDpCnt'
    QUADRANT_LEVERAGE_POWERLINE_UPRISING_TIMING_LAG = 'QLevPwrlnUprLag'
    TWO_QUADRANT_UPRISING_TIMING_LAG_MAJOR = '2QUprLagMaj'
    MAINSTREAM_LEADIN_BEFORE_MINOR = 'MsLeadinBfMin'
    BS_STAR_UP_BEFORE_MAJOR = 'BSStarUpBfMaj'
    BS_STAR_DOWN_BEFORE_MAJOR = 'BSStarDwnBfMaj'
    MAINSTREAM_LEADIN_BEFORE = 'MsLeadinBf'
    QUADRANT_TRIGGER_CREDIT = 'QuadTrgCred'
    QUADRANT_LEVERAGE_MACD_LEADIN_UB = 'QLevMACDLinUb'
